[tox]
requires =
    tox >= 4.20
env_list =
    py313
    py312
    py311

[testenv]
basepython =
    py313: python3.13
    py312: python3.12
    py311: python3.11
deps =
    pytest
    .[wxc,test,geobenchv2]
commands = pytest -s -v tests

[testenv:integration-vllm-{py313,py312,py311}]
description = Run vLLM (release) integration tests with Python {envname} (optional)
deps =
    pytest
    .[vllm,vllm_test]
commands = pytest -r A -vv integrationtests/vLLM

[testenv:integration-vllm-main-{py313,py312,py311}]
description = Run vLLM (main) integration tests with Python {envname} (optional)
setenv =
    VLLM_USE_PRECOMPILED = 1
    ; If the run fails because vLLM cannot find a precompiled wheel,
    ; set the value of VLLM_PRECOMPILED_WHEEL_LOCATION env variable to the output of the command below
    ;   curl -s https://wheels.vllm.ai/nightly/cu129/vllm/ | grep -oP 'href="[^"]*x86_64[^"]*\.whl"' | grep -oP '(?<=href=")[^"]*' | head -1 | sed 's|^\.\./\.\./\.\./|https://wheels.vllm.ai/|'
    ;
    ; VLLM_PRECOMPILED_WHEEL_LOCATION = {URL FROM CURL}
deps =
    pytest
    .[vllm,vllm_test]
    https://github.com/vllm-project/vllm.git
    
commands = 
    pytest -r A -vv integrationtests/vLLM
