[tox]
requires =
    tox >= 4.20
env_list =
    py313
    py312
    py311

[testenv]
basepython =
    py313: python3.13
    py312: python3.12
    py311: python3.11
deps =
    pytest
    .[wxc,test,geobenchv2]
commands = pytest -s -v tests

[testenv:integration-vllm-{py313,py312,py311}]
description = Run vLLM integration tests with Python {envname} (optional)
deps =
    .[vllm,vllm_test]
commands = pytest -s -v integrationtests/vLLM
