[tox]
requires =
    tox >= 4.20
env_list =
    3.13
    3.12
    3.11

[testenv]
deps =
    .[wxc,test,geobenchv2]
commands = pytest -s -v tests

[testenv:integration-vllm-{3.13,3.12,3.11}]
description = Run vLLM integration tests with Python {envname} (optional)
deps =
    .[vllm,vllm_test]
commands = pytest -s -v integrationtests/vLLM
